name: XcraftSignGate

main: me.INemesisI.XcraftSignGate.XcraftSignGate

version: 1.0
        
permissions:
    XcraftSignGate.*:
        description: Access to all commands this plugin provides
        children:
            XcraftSignGate.use: true
            XcraftSignGate.create: true
        default: op
        
    XcraftSignGate.use:
        description: Acces to use [Lift Up/Down]
    XcraftSignGate.create:
        description: Acces to create [Lift Up/Down] 